name: exam2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '3.19.6'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  socket_io_client: ^2.0.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get: 4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

